[package]
name = "mvar"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle = { version = "0.0.5", optional = true }

[dev-dependencies]
